//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public int id { get; set; }
        public int car_id { get; set; }
        public int object_form_id { get; set; }
        public int object_to_id { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual car car { get; set; }
        public virtual @object @object { get; set; }
        public virtual @object object1 { get; set; }
    }
}
